/* eslint-disable */
// This file is auto-generated by TanStack Router
// Do not edit manually — run `bun dev` or `bun build` to regenerate.

import { createFileRoute, createRootRouteWithContext } from '@tanstack/react-router'

import type { QueryClient } from '@tanstack/react-query'

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'
import { Route as ShopRoute } from './routes/shop'
import { Route as WishlistRoute } from './routes/wishlist'
import { Route as ProductIdRoute } from './routes/product.$id'
import { Route as CollectionSlugRoute } from './routes/collection.$slug'

const rootTree = rootRoute.addChildren([
  IndexRoute,
  ShopRoute,
  WishlistRoute,
  ProductIdRoute,
  CollectionSlugRoute,
])

export const routeTree = rootTree

export type FileRouteTypes = {
  fileRoutesByFullPath: {
    '/': typeof IndexRoute
    '/shop': typeof ShopRoute
    '/wishlist': typeof WishlistRoute
    '/product/$id': typeof ProductIdRoute
    '/collection/$slug': typeof CollectionSlugRoute
  }
  to: '/' | '/shop' | '/wishlist' | '/product/$id' | '/collection/$slug'
  id: '__root__' | '/' | '/shop' | '/wishlist' | '/product/$id' | '/collection/$slug'
  fileRoutesById: {
    '__root__': typeof rootRoute
    '/': typeof IndexRoute
    '/shop': typeof ShopRoute
    '/wishlist': typeof WishlistRoute
    '/product/$id': typeof ProductIdRoute
    '/collection/$slug': typeof CollectionSlugRoute
  }
}

declare module '@tanstack/react-router' {
  interface FileRouteTypes extends FileRouteTypes {}
}
